<a href="https://colab.research.google.com/github/sebastianlozadahernandez/Trabajos-Python-1/blob/main/ACTIVIDAD_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# EJERCICIO 1
print("EJERCICIO 1")

import numpy as np
# 1)Crear una matriz de 3x3 con todos los valores True
matriz_true = np.ones((3, 3), dtype=bool)
print("1) Matriz 3x3 con valores True:")
print(matriz_true)

# 2)Reemplazar todos los números impares por -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print("\n2) Arreglo con números impares reemplazados por -1:")
print(arr)

# 3)Convertir un array 1D en uno 2D con dos filas y la misma cantidad de elementos
arr2 = np.arange(16)
arr2_2D = arr2.reshape(2, 8)  # 2 filas, 8 columnas
print("\n3) Array 1D convertido en 2D:")
print(arr2_2D)

# 4)Convierte los vectores fila a y b en un vector columna
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
print(a)
print(b)
# Apilar verticalmente los vectores a y b
print("\n4) Apilar verticalmente los vectores a y b:")
c = np.hstack((a, b))
print(c)

# 5)Identificar elementos iguales en a y b
print("\n5) Identificar elementos iguales en a y b:")
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

iguales = np.where(a == b)
print(iguales)
print(a[iguales])

# 6)Intercambiar las columnas 1 y 2 en el array arr
print("\n6) Intercambiar las columnas 1 y 2 en el array arr:")
arr = np.arange(9).reshape(3, 3)
arr[:, [0, 1]] = arr[:, [1, 0]]
print(arr)

# EJERCICIO 2
print("EJERCICIO 2")

# Librearia que contiene el conjunto de tados llamados iris
from sklearn.datasets import load_iris
from scipy import stats

# Utilizamos la funcion load_iris() para cargar los datos
dataset = load_iris()

# Inspecciones un poco los datos , tenga encuenta que los datos vienen en forma de diccionario
dataset.keys()

# Veamos la descripcion del data set
dataset['DESCR']

# Veamos el nombre de las caracteristicas
dataset['feature_names']

# Veamos las etiquetas
dataset['filename']

# Separemos los datos
X = dataset['data'][: , [0,1]]

# 1)Obtenga el valor maximo y el valor minimo de la matriz X, luego obtenga el valor maximo y minimo de cada una de las columnas (esto es cada una de las caracteristicas)}
print("\n1) valor maximo y el valor minimo de la matriz X y valor maximo y minimo de cada una de las columnas")

# Valor máximo y mínimo de toda la matriz X
print("=== Valor máximo y mínimo de toda la matriz X ===\n")
max_total = np.max(X)
min_total = np.min(X)

print("Valor máximo de toda la matriz X:", max_total)
print("Valor mínimo de toda la matriz X:", min_total)

# Valor máximo y mínimo de cada columna (cada característica)
print("=== Valor máximo y mínimo de cada columna ===\n")
max_por_columna = np.max(X, axis=0)
min_por_columna = np.min(X, axis=0)

print("\nValores máximos por característica:")
print(max_por_columna)

print("\nValores mínimos por característica:")
print(min_por_columna)

# 2️)Calcular media, mediana, moda y desviación estándar para cada característica
print("\n2) Media, mediana, moda y desviación estándar para cada característica")

features = dataset['feature_names']
print("=== Media, mediana, moda y sd por característica ===\n")
for i in range(X.shape[1]):
    columna = X[:, i]
    nombre = features[i]
    media = np.mean(columna)
    mediana = np.median(columna)
    moda = stats.mode(columna, keepdims=True).mode[0]
    desviacion = np.std(columna)

    print(f"{nombre}:")
    print(f"  Media: {media:.2f}")
    print(f"  Mediana: {mediana:.2f}")
    print(f"  Moda: {moda:.2f}")
    print(f"  Desviación estándar: {desviacion:.2f}\n")

# 3️)Cantidad de valores mayores a la media y cuartiles de una variable
print("\n3) Valores mayores a la media y cuartiles de una variable")

print("=== Valores mayores a la media y cuartiles de una variable ===\n")
for i in range(X.shape[1]):
    columna = X[:, i]
    nombre = features[i]
    media = np.mean(columna)
    mayores_media = np.sum(columna > media)
    print(f"{nombre}: {mayores_media} valores mayores a la media")

EJERCICIO 1
1) Matriz 3x3 con valores True:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

2) Arreglo con números impares reemplazados por -1:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]

3) Array 1D convertido en 2D:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]

4) Apilar verticalmente los vectores a y b:
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]

5) Identificar elementos iguales en a y b:
(array([1, 3, 5, 7]),)
[2 2 4 4]

6) Intercambiar las columnas 1 y 2 en el array arr:
[[1 0 2]
 [4 3 5]
 [7 6 8]]
EJERCICIO 2

1) valor maximo y el valor minimo de la matriz X y valor maximo y minimo de cada una de las columnas
=== Valor máximo y mínimo de toda la matriz X ===

Valor máximo de toda la matriz X: 7.9
Valor mínimo de toda la matriz X: 2.0
=== Valor máximo y mínimo de cada columna ===


Valores máximos por característica:
[7.9 4.4]

Valores mínimos por característica:
[4.3 2. ]

2) Media, mediana, moda y desviaci